name: Teste, build e push

on:
  push:
    branches:
      - '*'

jobs:

  test:
    runs-on: ubuntu-local

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configurando versão do Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalando dependencias
      run: npm install

    - name: Testando aplicação
      run: npm test

  build:

    runs-on: ubuntu-local

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build e tag da imagem
      run: docker build -t luizfilipesm/waycarbon:latest .

    - name: Login no Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push da imagem
      if: github.ref == 'refs/heads/main'
      run: docker push luizfilipesm/waycarbon:latest
