name: Build e push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-local
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Substituir variáveis no código de backend
        run: |
          sed -i "s/\FRONTEND_URL/${{ vars.FRONTEND_URL }}/g" server.js

      - name: Build e tag da imagem
        run: docker build -t luizfilipesm/waycarbon:latest .

      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push da imagem
        run: docker push luizfilipesm/waycarbon:latest
